#pragma once

#include "NativeGameplayTags.h"

namespace JMHideTags
{
    JMHIDERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Locker);
    JMHIDERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Wardrobe);
    JMHIDERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Cabinet);
    JMHIDERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_UnderBed);
    JMHIDERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_UnderDesk);
    JMHIDERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_UnderTable);
    JMHIDERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Entered);
    JMHIDERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Exited);
}
