#pragma once

#include "NativeGameplayTags.h"

namespace JMEnemyTags
{
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Idle);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Patrol);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Investigate);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Chase);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Search);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Flee);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hide);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enraged);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Watcher_Frozen);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crawler_Stalk);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crawler_ReApproach);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crawler_FrenzyChase);

    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Melee);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Scream);

    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event);
    JMMONSTERFRAMEWORKRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Stimulus);

    /** Accepts any concrete state below JM.Enemy.State, including future enemy-specific states. */
    JMMONSTERFRAMEWORKRUNTIME_API bool IsConcreteState(const FGameplayTag& Tag);
    JMMONSTERFRAMEWORKRUNTIME_API bool IsConcreteAction(const FGameplayTag& Tag);
}
