#pragma once

#include "NativeGameplayTags.h"

namespace JMJumpScareEventTags
{
    JMJUMPSCARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(JumpScare);
    JMJUMPSCARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Started);
    JMJUMPSCARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Impact);
    JMJUMPSCARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Exiting);
    JMJUMPSCARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Finished);
    JMJUMPSCARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cancelled);
    JMJUMPSCARE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Failed);
}
