#pragma once

#include "CoreMinimal.h"
#include "Actors/JMGridMapGenerator.h"
#include "GameFramework/Actor.h"
#include "JMCustomGridMapGenerator.generated.h"

class AJMRoomModule;
class UArrowComponent;
class UJMRoomDefinition;
class USceneComponent;

/** One user-authored cell. North is +Y, East is +X in the custom grid. */
USTRUCT(BlueprintType)
struct JMROOMGRIDRUNTIME_API FJMCustomGridCell
{
    GENERATED_BODY()

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Cell")
    FJMGridCoordinate Coordinate;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Cell")
    bool bEnabled = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Cell", meta=(Bitmask, BitmaskEnum="/Script/JMRoomGridRuntime.EJMRoomDirection", EditCondition="bEnabled"))
    int32 OpenDirections = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Cell", meta=(EditCondition="bEnabled"))
    bool bEntrance = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Cell", meta=(EditCondition="bEnabled"))
    bool bExit = false;

    /** When set, this exact definition is used instead of the weighted random library. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Cell|Special", meta=(EditCondition="bEnabled"))
    TSoftObjectPtr<UJMRoomDefinition> SpecialRoomDefinition;

    EJMRoomDirection GetDirectionMask() const
    {
        return static_cast<EJMRoomDirection>(OpenDirections & static_cast<int32>(EJMRoomDirection::All));
    }
};

/**
 * Independent, user-authored grid generator. It intentionally does not derive from or mutate the
 * standard fixed 5x5 generator, so existing levels and Blueprint defaults keep their old behavior.
 */
UCLASS(Blueprintable)
class JMROOMGRIDRUNTIME_API AJMCustomGridMapGenerator : public AActor
{
    GENERATED_BODY()

public:
    AJMCustomGridMapGenerator();

    virtual void BeginPlay() override;

#if WITH_EDITOR
    virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
#endif

    UFUNCTION(CallInEditor, BlueprintCallable, Category="JM Room Grid|Custom Grid", meta=(DisplayName="Synchronize Cells To Grid Size"))
    void SynchronizeGridCells();

    UFUNCTION(BlueprintCallable, Category="JM Room Grid|Custom Grid")
    bool SetCell(int32 X, int32 Y, bool bEnabled, int32 OpenDirections, bool bEntrance = false, bool bExit = false);

    UFUNCTION(BlueprintPure, Category="JM Room Grid|Custom Grid")
    FJMCustomGridCell GetCellChecked(int32 X, int32 Y) const;

    UFUNCTION(BlueprintPure, Category="JM Room Grid|Custom Grid")
    FVector GridToLocalLocation(FJMGridCoordinate Coordinate) const;

    UFUNCTION(BlueprintCallable, Category="JM Room Grid|Validation")
    FJMRoomValidationResult ValidateGridDesign() const;

    UFUNCTION(CallInEditor, Category="JM Room Grid|Validation", meta=(DisplayName="Validate Custom Grid"))
    void ValidateGridDesignInEditor() const;

    UFUNCTION(BlueprintCallable, Category="JM Room Grid|Generation", meta=(DisplayName="Generate Custom Preview (With Result)"))
    bool GeneratePreview();

    UFUNCTION(CallInEditor, Category="JM Room Grid|Generation", meta=(DisplayName="Generate Custom Preview"))
    void GeneratePreviewInEditor();

    UFUNCTION(CallInEditor, BlueprintCallable, Category="JM Room Grid|Generation")
    void ClearPreview();

    /** Clears only rooms generated by custom generators; legacy generated rooms are untouched. */
    UFUNCTION(CallInEditor, BlueprintCallable, Category="JM Room Grid|Generation", meta=(DisplayName="Clear All Custom Generated Rooms In Level"))
    void ClearAllCustomGeneratedRoomsInLevel();

    UFUNCTION(BlueprintCallable, Category="JM Room Grid|Generation", meta=(DisplayName="Regenerate Custom Same Seed (With Result)"))
    bool RegenerateSameSeed();

    UFUNCTION(CallInEditor, Category="JM Room Grid|Generation", meta=(DisplayName="Regenerate Custom Same Seed"))
    void RegenerateSameSeedInEditor();

    UFUNCTION(BlueprintCallable, Category="JM Room Grid|Generation", meta=(DisplayName="Generate Custom New Seed (With Result)"))
    bool GenerateNewSeed();

    UFUNCTION(CallInEditor, Category="JM Room Grid|Generation", meta=(DisplayName="Generate Custom New Seed"))
    void GenerateNewSeedInEditor();

    UFUNCTION(BlueprintCallable, Category="JM Room Grid|Validation")
    FJMRoomValidationResult ValidateGeneratedMap() const;

    UFUNCTION(CallInEditor, Category="JM Room Grid|Validation", meta=(DisplayName="Validate Custom Generated Map"))
    void ValidateGeneratedMapInEditor() const;

    UFUNCTION(CallInEditor, BlueprintCallable, Category="JM Room Grid|Debug")
    void DrawGridDesign() const;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> GeneratorRoot;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UArrowComponent> EntranceMarker;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UArrowComponent> ExitMarker;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Custom Grid", meta=(ClampMin="1", ClampMax="100"))
    int32 GridWidth = 5;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Custom Grid", meta=(ClampMin="1", ClampMax="100"))
    int32 GridHeight = 5;

    /** Row-major editor cells. Use Synchronize after changing Width/Height; existing coordinates are preserved. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Custom Grid", meta=(TitleProperty="Coordinate"))
    TArray<FJMCustomGridCell> Cells;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Grid", meta=(ClampMin="1.0"))
    float RoomCellSize = 5200.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Grid", meta=(ClampMin="1.0"))
    float RoomHeight = 500.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Selection")
    TArray<TSoftObjectPtr<UJMRoomDefinition>> RoomDefinitions;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Random")
    int32 RandomSeed = 1337;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Random")
    bool bUseRandomSeed = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Generation")
    bool bGenerateOnBeginPlay = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Generation")
    bool bGenerateInEditor = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Generation|Preview")
    bool bHideCeilingsForPreview = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Debug")
    bool bShowDebug = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Debug", meta=(EditCondition="bShowDebug"))
    bool bShowCoordinates = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Debug", meta=(EditCondition="bShowDebug"))
    bool bShowPortDirections = true;

    UPROPERTY(Transient, VisibleInstanceOnly, BlueprintReadOnly, Category="Generation")
    TArray<FJMGeneratedRoomRecord> GeneratedRooms;

private:
    bool GenerateInternal(int32 EffectiveSeed);
    const FJMCustomGridCell* FindCell(int32 X, int32 Y) const;
    FJMCustomGridCell* FindCell(int32 X, int32 Y);
    void UpdateRoleMarkers();
    void DrawGeneratedDebug() const;
};
