#pragma once

#include "NativeGameplayTags.h"

namespace JMDialogueEventTags
{
    REUSABLEDIALOGUESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dialogue);
    REUSABLEDIALOGUESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Started);
    REUSABLEDIALOGUESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Finished);
    REUSABLEDIALOGUESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ChoiceSelected);
}
