#pragma once

#include "NativeGameplayTags.h"

namespace JMObjectiveFlowEventTags
{
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ObjectiveFlow);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Started);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StepChanged);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Completed);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Failed);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stopped);
}

