#pragma once

#include "NativeGameplayTags.h"

namespace JMObjectiveEventTags
{
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Objective);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Registered);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Activated);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Progressed);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Completed);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Failed);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Deactivated);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reset);
    JMOBJECTIVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Removed);
}
