#pragma once
#include "NativeGameplayTags.h"

namespace JMThrowableEventTags
{
    JMTHROWABLE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Thrown);
    JMTHROWABLE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bounced);
    JMTHROWABLE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rested);
    JMTHROWABLE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Activated);
    JMTHROWABLE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Burst);
    JMTHROWABLE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Finished);
}
