#pragma once

#include "NativeGameplayTags.h"

namespace JMInteractionEventTags
{
    JMINTERACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction);
    JMINTERACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Succeeded);
    JMINTERACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Failed);
    JMINTERACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FocusStarted);
    JMINTERACTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FocusEnded);
}
