#pragma once

#include "NativeGameplayTags.h"

namespace JMDoorEventTags
{
    JMDOORRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Door);
    JMDOORRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Opened);
    JMDOORRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Closed);
    JMDOORRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Locked);
    JMDOORRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unlocked);
    JMDOORRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Broken);
}
