;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="JumpScare.Test.Monster",DevComment="")
+GameplayTagList=(Tag="JumpScare.Trigger.Test.01",DevComment="")
+GameplayTagList=(Tag="Objective.Main.GetOfficeKey",DevComment="")
+GameplayTagList=(Tag="Objective.Main.OpenOfficeDoor",DevComment="")
+GameplayTagList=(Tag="Objective.Main.TalkToTeacher",DevComment="")
+GameplayTagList=(Tag="ObjectiveFlow.Main.EnterOffice",DevComment="")
+GameplayTagList=(Tag="Prototype.Objective.CollectSlime",DevComment="Collect three slime samples")
+GameplayTagList=(Tag="Prototype.Objective.SubmitSlime",DevComment="Submit collected slime samples at base")
+GameplayTagList=(Tag="Prototype.Flow.FirstRun",DevComment="Base Upgrade minimum prototype loop")

